# Generated by Django 5.0.3 on 2024-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(choices=[('t', 'training'), ('w', 'walking'), ('h', 'hotel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(choices=[('i', 'individual'), ('g', 'group')], max_length=50),
        ),
    ]
