# Generated by Django 5.0.3 on 2024-04-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(choices=[('Training', 'Training'), ('Walking', 'Walking'), ('Hotel', 'Hotel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author'),
        ),
    ]
