# Generated by Django 5.0.3 on 2024-04-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_price_service_alter_price_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
